#!/bin/sh
#
# Startup script for the OOPS FireWall
#
# chkconfig: 345 50 50
# description: OOPS Firewall is firewall that used IPTABLES in kernel 2.4.x
# processname: oops_firewall
# config: /etc/oops_firewall

# Source function library.
. /etc/rc.d/init.d/functions

ERR_FILE=/tmp/oops_firewall_err

case "$1" in
  start)
    echo -n "Starting OOPS Firewall: "
    /usr/sbin/oops_firewall > /dev/null 2> ${ERR_FILE}

    if [ "$(cat ${ERR_FILE} 2>/dev/null)" != "" ]; then
      echo_failure
    else
      echo_success
      touch /var/lock/subsys/oops_firewall
    fi
    rm -rf $ERR_FILE > /dev/null 2>&1
    echo
    ;;
  stop)
    iptables -P INPUT ACCEPT
    iptables -F INPUT
    rm -rf /var/lock/subsys/oops_firewall
    echo -n "Destory Firewall Tables: "
    echo_success
    echo
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    iptables -L -v
    ;;
  *)
    echo -n "Usage: $0 {start|stop|restart|status}"
esac

exit 0
