#!/bin/sh
#
# $Id: oops-firewall.init,v 1.11 2004-08-04 14:46:50 oops Exp $
#
# Startup script for the OOPS FireWall
#
# chkconfig: 345 99 10
# description: OOPS Firewall is firewall that used IPTABLES in kernel 2.4.x
# processname: oops_firewall
# config: /etc/oops_firewall

# Source function library.
. /etc/rc.d/init.d/functions

ERR_FILE=/tmp/oops_firewall_err
IPTABLES=/sbin/iptables

case "$1" in
  start)
    echo -n "Starting OOPS Firewall: "
    /usr/sbin/oops_firewall > /dev/null 2> ${ERR_FILE}

    if [ "$(cat ${ERR_FILE} 2>/dev/null)" != "" ]; then
      echo_failure
      ${IPTABLES} -Z
      ${IPTABLES} -P INPUT ACCEPT
      ${IPTABLES} -F INPUT
      ${IPTABLES} -P OUTPUT ACCEPT
      ${IPTABLES} -F OUTPUT
      ${IPTABLES} -t nat -Z
      ${IPTABLES} -t nat -P PREROUTING ACCEPT
      ${IPTABLES} -t nat -F PREROUTING
      ${IPTABLES} -t nat -P POSTROUTING ACCEPT
      ${IPTABLES} -t nat -F POSTROUTING
      ${IPTABLES} -t mangle -Z
      ${IPTABLES} -t mangle -P PREROUTING ACCEPT
      ${IPTABLES} -t mangle -F PREROUTING
      ${IPTABLES} -t mangle -P OUTPUT ACCEPT
      ${IPTABLES} -t mangle -F OUTPUT
      echo 0 > /proc/sys/net/ipv4/ip_forward
    else
      echo_success
      touch /var/lock/subsys/oops_firewall
    fi
    rm -rf $ERR_FILE > /dev/null 2>&1
    echo
    ;;
  stop)
    ${IPTABLES} -Z
    ${IPTABLES} -P INPUT ACCEPT
    ${IPTABLES} -F INPUT
    ${IPTABLES} -t nat -Z
    ${IPTABLES} -t nat -P PREROUTING ACCEPT
    ${IPTABLES} -t nat -F PREROUTING
    ${IPTABLES} -t nat -P POSTROUTING ACCEPT
    ${IPTABLES} -t nat -F POSTROUTING
    ${IPTABLES} -t mangle -Z
    ${IPTABLES} -t mangle -P PREROUTING ACCEPT
    ${IPTABLES} -t mangle -F PREROUTING
    ${IPTABLES} -t mangle -P OUTPUT ACCEPT
    ${IPTABLES} -t mangle -F OUTPUT
    echo 0 > /proc/sys/net/ipv4/ip_forward
    rm -rf /var/lock/subsys/oops_firewall
    echo -n "Destory Firewall Tables: "
    echo_success
    echo
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    echo
    echo
    echo "[1;31m[ Legualar Table ][7;0m"
    echo "[1;31m-----------------------------------------------------------------------[7;0m"
    echo
    ${IPTABLES} -L -v
    echo
    echo
    echo "[1;31m[ NAT Table ][7;0m"
    echo "[1;31m-----------------------------------------------------------------------[7;0m"
    echo
    ${IPTABLES} -t nat -L -v
    echo
    echo
    echo "[1;31m[ MANGLE Table ][7;0m"
    echo "[1;31m-----------------------------------------------------------------------[7;0m"
    echo
    ${IPTABLES} -t mangle -L -v
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac

exit 0
