.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH oops-firewall 8 "May 2, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
oops-firewall \- Simple and forceful frontend of iptables
.SH SYNOPSIS
.B oops-firewall
.RI [ options ]
.br
.TP 4
.B Options:
.nf
-c conf_dir  set directory that include configuration file
-t           execute test mode
-v           print verbose messages
-n           don't print ansi code
-V           print current version
-h           help messages (this messages)
.fi
.SH DESCRIPTION
oops-firewall keeps your network system basically secure for external access
with iptables package in KERNEL v2.4 or v2.6.

.SH AUTHOR
JoungKyun Kim <admin@oops.org> 02 May, 2009

.SH BUG
Report bug to <admin@oops.org>
